### ISSUE TITLE
links in evidences lead nowhere

### ISSUE THREAD

**Issue by shubhsingh594** [joebowen/model_completion_dashboard#10]
<img width="1213" alt="evi" src="https://cloud.githubusercontent.com/assets/15982349/23351225/e5a4c170-fce5-11e6-9c78-68772da4ce01.png">

clicking on the links in the evidences page, throws error, also i guess the links are not getting rendered properly.

@joebowen any suggestions about fixing this.

**Comment by jamiebbowen** [comment]
Hard to say what's going on here without that error that's most likely
getting thrown on the backend.  But my best guess is that the pyopenworm
api has changed and the model completion dashboard isn't making a valid api
call.

**Comment by shubhsingh594** [comment]
@joebowen  i think i got the problem , the values used as keys to get the details of the evidences , are mentioned as optional in the documentation , https://pyopenworm.readthedocs.io/en/latest/_modules/PyOpenWorm/evidence.html#Evidence , and hence, when they return empty the links crash ...
Will make a PR to fix this soon
